package com.hospital.dao;

import com.hospital.dao.dataobject.DoctorDO;

public interface DoctorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Wed Feb 10 16:22:23 CST 2021
     */
    int insert(DoctorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Wed Feb 10 16:22:23 CST 2021
     */
    int insertSelective(DoctorDO record);
}