package com.hospital.dao;

import com.hospital.dao.dataobject.DoctorDO;

public interface DoctorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Feb 16 11:19:59 CST 2021
     */
    int insert(DoctorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Tue Feb 16 11:19:59 CST 2021
     */
    int insertSelective(DoctorDO record);

    DoctorDO selectByPrimaryKey(Integer doctorId);

    void updateByPrimaryKeySelective(DoctorDO doctorDO);
}