package com.hospital.dao;

import com.hospital.dao.dataobject.HospitalDO;

import java.util.List;

public interface HospitalDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Wed Feb 10 12:04:27 CST 2021
     */
    int deleteByPrimaryKey(Integer hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Wed Feb 10 12:04:27 CST 2021
     */
    int insert(HospitalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Wed Feb 10 12:04:27 CST 2021
     */
    int insertSelective(HospitalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Wed Feb 10 12:04:27 CST 2021
     */
    HospitalDO selectByPrimaryKey(Integer hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Wed Feb 10 12:04:27 CST 2021
     */
    int updateByPrimaryKeySelective(HospitalDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Wed Feb 10 12:04:27 CST 2021
     */
    int updateByPrimaryKey(HospitalDO record);

    List<HospitalDO> getHospitalList();
}