package com.hospital.dao;

import com.hospital.dao.dataobject.PatientDO;

public interface PatientDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Thu Feb 18 23:51:30 CST 2021
     */
    int insert(PatientDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbg.generated Thu Feb 18 23:51:30 CST 2021
     */
    int insertSelective(PatientDO record);
}