package com.hospital.dao;

import com.hospital.dao.dataobject.PrescriptionDO;

import java.util.List;

public interface PrescriptionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Wed Feb 17 16:41:42 CST 2021
     */
    int deleteByPrimaryKey(Integer prescriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Wed Feb 17 16:41:42 CST 2021
     */
    int insert(PrescriptionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Wed Feb 17 16:41:42 CST 2021
     */
    int insertSelective(PrescriptionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Wed Feb 17 16:41:42 CST 2021
     */
    PrescriptionDO selectByPrimaryKey(Integer prescriptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Wed Feb 17 16:41:42 CST 2021
     */
    int updateByPrimaryKeySelective(PrescriptionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbg.generated Wed Feb 17 16:41:42 CST 2021
     */
    int updateByPrimaryKey(PrescriptionDO record);


    List<PrescriptionDO> selectByDoctorId(Integer doctorId);
}