package com.hospital.dao;

import com.hospital.dao.dataobject.ProcessDO;

public interface ProcessDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int insert(ProcessDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int insertSelective(ProcessDO record);
}