package com.hospital.dao;

import com.hospital.dao.dataobject.UserDO;

import java.util.List;


public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    UserDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    int updateByPrimaryKey(UserDO record);

    UserDO selectByAccountId(String username);


}