package com.hospital.dao;

import com.hospital.dao.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    UserDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital_hub_user
     *
     * @mbg.generated Tue Feb 16 10:50:49 CST 2021
     */
    int updateByPrimaryKey(UserDO record);

    UserDO selectByAccountId(String accountId);
}