package com.hospital.dao.dataobject;

import java.util.List;

public class DepartmentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_id
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.hospital_id
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_name
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.doctor_id_list
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    private List<Integer> doctorIdList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.remain
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    private Integer remain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.waiting
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    private Integer waiting;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_id
     *
     * @return the value of department.department_id
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_id
     *
     * @param departmentId the value for department.department_id
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.hospital_id
     *
     * @return the value of department.hospital_id
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.hospital_id
     *
     * @param hospitalId the value for department.hospital_id
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.doctor_id_list
     *
     * @return the value of department.doctor_id_list
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public List<Integer> getDoctorIdList() {
        return doctorIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.doctor_id_list
     *
     * @param doctorIdList the value for department.doctor_id_list
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public void setDoctorIdList(List<Integer> doctorIdList) {
        this.doctorIdList = doctorIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.remain
     *
     * @return the value of department.remain
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public Integer getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.remain
     *
     * @param remain the value for department.remain
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public void setRemain(Integer remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.waiting
     *
     * @return the value of department.waiting
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public Integer getWaiting() {
        return waiting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.waiting
     *
     * @param waiting the value for department.waiting
     *
     * @mbg.generated Wed Feb 10 16:14:56 CST 2021
     */
    public void setWaiting(Integer waiting) {
        this.waiting = waiting;
    }
}