package com.hospital.dao.dataobject;

import java.util.Date;

public class PrescriptionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private Integer prescriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.registration_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private String registrationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.patient_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private Integer patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.doctor_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_time
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private Date prescriptionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.prescription_detail
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private String prescriptionDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.status
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.medicine_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private String medicineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.total_price
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    private Double totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_id
     *
     * @return the value of prescription.prescription_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public Integer getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_id
     *
     * @param prescriptionId the value for prescription.prescription_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setPrescriptionId(Integer prescriptionId) {
        this.prescriptionId = prescriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.registration_id
     *
     * @return the value of prescription.registration_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.registration_id
     *
     * @param registrationId the value for prescription.registration_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId == null ? null : registrationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.patient_id
     *
     * @return the value of prescription.patient_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public Integer getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.patient_id
     *
     * @param patientId the value for prescription.patient_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.doctor_id
     *
     * @return the value of prescription.doctor_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.doctor_id
     *
     * @param doctorId the value for prescription.doctor_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_time
     *
     * @return the value of prescription.prescription_time
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public Date getPrescriptionTime() {
        return prescriptionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_time
     *
     * @param prescriptionTime the value for prescription.prescription_time
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setPrescriptionTime(Date prescriptionTime) {
        this.prescriptionTime = prescriptionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.prescription_detail
     *
     * @return the value of prescription.prescription_detail
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public String getPrescriptionDetail() {
        return prescriptionDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.prescription_detail
     *
     * @param prescriptionDetail the value for prescription.prescription_detail
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setPrescriptionDetail(String prescriptionDetail) {
        this.prescriptionDetail = prescriptionDetail == null ? null : prescriptionDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.status
     *
     * @return the value of prescription.status
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.status
     *
     * @param status the value for prescription.status
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.medicine_id
     *
     * @return the value of prescription.medicine_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public String getMedicineId() {
        return medicineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.medicine_id
     *
     * @param medicineId the value for prescription.medicine_id
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId == null ? null : medicineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.total_price
     *
     * @return the value of prescription.total_price
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.total_price
     *
     * @param totalPrice the value for prescription.total_price
     *
     * @mbg.generated Thu Feb 18 23:18:40 CST 2021
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
}