package com.hospital.dao.dataobject;

public class ProcessDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.registration_id
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    private String registrationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.doctor_id
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    private Integer doctorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.description
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    private Object description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.accessory_name
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    private String accessoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.accessory_url
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    private String accessoryUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column process.state
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.registration_id
     *
     * @return the value of process.registration_id
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.registration_id
     *
     * @param registrationId the value for process.registration_id
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId == null ? null : registrationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.doctor_id
     *
     * @return the value of process.doctor_id
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public Integer getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.doctor_id
     *
     * @param doctorId the value for process.doctor_id
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public void setDoctorId(Integer doctorId) {
        this.doctorId = doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.description
     *
     * @return the value of process.description
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public Object getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.description
     *
     * @param description the value for process.description
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public void setDescription(Object description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.accessory_name
     *
     * @return the value of process.accessory_name
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public String getAccessoryName() {
        return accessoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.accessory_name
     *
     * @param accessoryName the value for process.accessory_name
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public void setAccessoryName(String accessoryName) {
        this.accessoryName = accessoryName == null ? null : accessoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.accessory_url
     *
     * @return the value of process.accessory_url
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public String getAccessoryUrl() {
        return accessoryUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.accessory_url
     *
     * @param accessoryUrl the value for process.accessory_url
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public void setAccessoryUrl(String accessoryUrl) {
        this.accessoryUrl = accessoryUrl == null ? null : accessoryUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column process.state
     *
     * @return the value of process.state
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column process.state
     *
     * @param state the value for process.state
     *
     * @mbg.generated Sun Feb 07 00:45:59 CST 2021
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}