package com.hospital.dao.dataobject;

import java.util.ArrayList;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.user_id
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.username
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.password
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.email
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.balance
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.portrait_url
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String portraitUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.order_id_list
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private Object orderIdList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.tag
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.true_name
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String trueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.gender
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_hub_user.age
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.user_id
     *
     * @return the value of hospital_hub_user.user_id
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.user_id
     *
     * @param userId the value for hospital_hub_user.user_id
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.username
     *
     * @return the value of hospital_hub_user.username
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.username
     *
     * @param username the value for hospital_hub_user.username
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.password
     *
     * @return the value of hospital_hub_user.password
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.password
     *
     * @param password the value for hospital_hub_user.password
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.email
     *
     * @return the value of hospital_hub_user.email
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.email
     *
     * @param email the value for hospital_hub_user.email
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.balance
     *
     * @return the value of hospital_hub_user.balance
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.balance
     *
     * @param balance the value for hospital_hub_user.balance
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.portrait_url
     *
     * @return the value of hospital_hub_user.portrait_url
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getPortraitUrl() {
        return portraitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.portrait_url
     *
     * @param portraitUrl the value for hospital_hub_user.portrait_url
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setPortraitUrl(String portraitUrl) {
        this.portraitUrl = portraitUrl == null ? null : portraitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.order_id_list
     *
     * @return the value of hospital_hub_user.order_id_list
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public ArrayList<Integer> getOrderIdList() {
        return (ArrayList<Integer>) orderIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.order_id_list
     *
     * @param orderIdList the value for hospital_hub_user.order_id_list
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setOrderIdList(Object orderIdList) {
        this.orderIdList = orderIdList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.tag
     *
     * @return the value of hospital_hub_user.tag
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.tag
     *
     * @param tag the value for hospital_hub_user.tag
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.true_name
     *
     * @return the value of hospital_hub_user.true_name
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.true_name
     *
     * @param trueName the value for hospital_hub_user.true_name
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.gender
     *
     * @return the value of hospital_hub_user.gender
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.gender
     *
     * @param gender the value for hospital_hub_user.gender
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_hub_user.age
     *
     * @return the value of hospital_hub_user.age
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_hub_user.age
     *
     * @param age the value for hospital_hub_user.age
     *
     * @mbg.generated Mon Feb 08 16:45:52 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}